= Review Programming-Challenge Lösung für Kandidate XXXX
Benjamin Schmid <benjamin.schmid@exxcellent.de>
2018-06-27

Kontext: TODO:, z.B. Einsteiger mit Abschluss in Computer Science. Sprachlevel: ~B1.

.Verwendete Wertungssymbole 
[cols="1,10"]
|===
|`++`| sehr gut; übertrifft Forderung
|`+` | gut
|`o` | neutral – erfüllt Erwartungen
|`-` | nicht gut – erfüllt die Erwartugnen nicht
|`--`| sehr schlecht – grobe Mängel.
|===

== Management Summary und Fazit


<<<<
== Review im Detail

=== Vorgehensweise

* o/+: …


=== Tooling: Versionierung

* -: …

=== Tooling: Build & IDE

* o: …

=== Idiome

* o/-: …

=== Software-Entwurf: Problemzergliederung, Erweiterbarkeit

* -: …

=== Software-Entwurf: Datenmodell

* -: …

=== Software-Entwurf: Einlesen der Dateien

* ++: …


=== Software-Entwurf: Algorithmus, Berechnung & Korrektheit des Ergebnis

* o/-:…
* +: Das Ergebnis ist korrekt

=== Namen, Begrifflichkeiten & Dokumentation

* o: …

== Refactoring

* o/+: …

=== Robustheit, Resilency & Fehlerbehandlung

* …

=== Test-Driven Development

* o/-: …


=== Sorgfalt

* --: Generell stark mangelnde Sorgfalt und/oder Verständnis der Grundlagen. Vorgehen scheint eher Copy- & Paste-getrieben.

=== Diskussionthemen/Anregungen für Einstellungsgespräch

// Dinge die man mit dem Kandidaten z.B. im persönlichen Bewerbungsgespräch als 
// Aufhänger durchsprechen könnte. 

=== Ergebnisse der IDEA Codeanalyse mit `exxcellent2017.xml`
// Analyse starten, Export als HTML, im Browser Copy&Paste

…

----
Inspection tree:
    Error   34 errors 
        General group   4 errors 
            Line is longer than allowed by code style inspection   4 errors 
                file .classpath   1 error 
                    ERROR Line is longer than allowed by code style (> 140 columns) 
                file description   2 errors 
                    ERROR Line is longer than allowed by code style (> 140 columns) 
                    ERROR Line is longer than allowed by code style (> 140 columns) 
                file Ratschlag   1 error 
                    ERROR Line is longer than allowed by code style (> 140 columns) 
        Java group   30 errors 
            Code maturity group   7 errors 
                Call to 'printStackTrace()' inspection   7 errors 
            Javadoc group   3 errors 
                Missing 'package‑info.java' inspection   3 errors 
            Method metrics group   2 errors 
                Overly complex method inspection   2 errors 
            Naming conventions group   18 errors 
                Local variable naming convention inspection   17 errors 
                Package naming convention inspection   1 error 
    Warning   46 warnings 
        General group   14 warnings 
            Problematic whitespace inspection   10 warnings 
            TODO comment inspection   4 warnings 
        Ignore group   1 warning 
        Java group   18 warnings 
            Class structure group   3 warnings 
                Field can be local inspection   3 warnings 
            Code style issues group   1 warning 
                Unnecessary interface modifier inspection   1 warning 
            Declaration redundancy group   3 warnings 
                Redundant throws clause inspection   1 warning 
                Unused declaration inspection   2 warnings 
            Imports group   1 warning 
                Unused import inspection   1 warning 
            Java language level migration aids group   2 warnings 
                Java 7 group   2 warnings 
            Performance group   2 warnings 
                Redundant call to 'String.format()' inspection   2 warnings 
            Probable bugs group   2 warnings 
                Unused assignment inspection   2 warnings 
            Resource management group   4 warnings 
                AutoCloseable used without 'try'‑with‑resources inspection   2 warnings 
                I/O resource opened but not safely closed inspection   2 warnings 
        Properties Files group   13 warnings 
----


