= Review Programming-Challenge des Kandidaten XXXX
Benjamin Schmid <benjamin.schmid@exxcellent.de>
2020-01-01

== Management Summary und Fazit

=== Kontext des Kandidatens
//  z.B. Einsteiger mit Abschluss in Computer Science. Sprachlevel: ~B1.
TODO

=== Bewertung & Einschätzung
// zusammenfassende Einschätzung & Bewertung
TODO

<<<<
== Hinweise

// Verwendung
//   1. Andere Beispiele anssehen
//   2. der Struktur folgenden ausfüllen
//   3. PDF erzeugen & kommunizieren: `asciidoctor-pdf REVIEW.adoc`

link:https://www.exxcellent.de/confluence/display/XXINT/Hinweise+zur+Bewertung+der+eXXcellent+Programming+Challenge[
     Im Confluence findet man] Hinweise zu den Bewertungspunkten/Kriterien die sich unten in der Struktur wiederfinden

.Verwendete Wertungssymbole
:icons: font
:sgut: icon:thumbs-up[]
:gut: icon:check-circle[]
:ok: icon:ellipsis-h[]
:bad: icon:bolt[]
:vbad: icon:exclamation-triangle[]

[cols="1,10"]
|===
|{sgut}| sehr gut; übertrifft Forderung
|{gut} | gut
|{ok} | neutral – erfüllt Erwartungen
|{bad} | nicht gut – erfüllt die Erwartungen nicht
|{vbad}| sehr schlecht – grobe Mängel.
|===




== Review



=== Vorgehensweise

==== Vorgehensweise: Bearbeitung der Aufgabe

_Geschätzte Bearbeitungszeit:_ 

{gut}: …


==== Vorgehensweise: Refactoring




=== Tooling 

==== Tooling:  Versionsverwaltung & Versionierung
// Fortsetuzung der Historie, kleinteilige Commits, …

==== Tooling: Build & IDE
{ok}: …

{vbad}: …



=== Architektur

==== Software-Entwurf: Datenmodell
{bad}: …

{ok}: …


==== Software-Entwurf: Einlesen der Dateien
{sgut}: …


==== Software-Entwurf: Algorithmus, Berechnung & Korrektheit des Ergebnis
{gut}: …


==== Software-Entwurf: Problemzergliederung, Erweiterbarkeit
{ok}: …





=== Design & Codestyle

==== Code: Programmiersprache & Idiome
// Beherrscht er Sprachmittel, typische Idiome
{ok}: …


==== Design: Entwurfspattern
// setzt er Patterns ein. Sind diese sinnvoll eingesetzt
{ok}: …

==== Code: Namen & Begrifflichkeiten
// Sinnvolle und Klare Namen dort wo es wichtrig ist
{ok}: …

==== Code: Dokumentation
// Priorität der Dokumentation:
//    1. Doku der Konzepte & Pakete
//    2. Doku der Schnittstellen
//    3. Doku der Klassen & ihre Aufgaben.
//    4. Doku von Methoden & Parametern
//
// Inhalt der Dokumentation: Umschreibt er nur nochmals den Code (schlecht) oder Konzept & Ideen (gut)
{ok}: …






=== Qualität

==== Qualität: Robustheit, Resilency & Fehlerbehandlung
{ok}: …


==== Qualität: Test-Driven Development
{ok}: …


==== Qualität: Sorgfalt
{ok}: …


==== Qualität: Ergebnisse der IDEA Codeanalyse
// Wie ausführen:
//    1. Projekt in IDEA öffnen
//    2. Inspection Profile installieren.
//       Quelle: https://gitlab.exxcellent.de/exxcellent-technology/exxcellent-qa/blob/master/java/intellij-idea/.idea/inspectionProfiles/exxcellent-2018.xml
//    3. Analyse starten
//    4. Export als HTML, dann im Browser öffnen und betreffende bereiche Copy&Paste

.Bewertung des Analysergebnises
TODO:: Zwingend notwendig, da die Inspections teils Geschmackssache/Leitfaden teils kritische Probleme sein können.

.Ergebnis der Ausführung (Error & Warnings)
----
Inspection tree:
    Error   34 errors
        General group   4 errors
            Line is longer than allowed by code style inspection   4 errors
                file .classpath   1 error
                    ERROR Line is longer than allowed by code style (> 140 columns)
                file description   2 errors
                    ERROR Line is longer than allowed by code style (> 140 columns)
                    ERROR Line is longer than allowed by code style (> 140 columns)
                file Ratschlag   1 error
                    ERROR Line is longer than allowed by code style (> 140 columns)
        Java group   30 errors
            Code maturity group   7 errors
                Call to 'printStackTrace()' inspection   7 errors
            Javadoc group   3 errors
                Missing 'package‑info.java' inspection   3 errors
            Method metrics group   2 errors
                Overly complex method inspection   2 errors
            Naming conventions group   18 errors
                Local variable naming convention inspection   17 errors
                Package naming convention inspection   1 error
    Warning   46 warnings
        General group   14 warnings
            Problematic whitespace inspection   10 warnings
            TODO comment inspection   4 warnings
        Ignore group   1 warning
        Java group   18 warnings
            Class structure group   3 warnings
                Field can be local inspection   3 warnings
            Code style issues group   1 warning
                Unnecessary interface modifier inspection   1 warning
            Declaration redundancy group   3 warnings
                Redundant throws clause inspection   1 warning
                Unused declaration inspection   2 warnings
            Imports group   1 warning
                Unused import inspection   1 warning
            Java language level migration aids group   2 warnings
                Java 7 group   2 warnings
            Performance group   2 warnings
                Redundant call to 'String.format()' inspection   2 warnings
            Probable bugs group   2 warnings
                Unused assignment inspection   2 warnings
            Resource management group   4 warnings
                AutoCloseable used without 'try'‑with‑resources inspection   2 warnings
                I/O resource opened but not safely closed inspection   2 warnings
        Properties Files group   13 warnings
----


<<<
== Diskussionthemen/Anregungen für Einstellungsgespräch

NOTE:: Dinge die man mit dem Kandidaten z.B. im persönlichen Bewerbungsgespräch als Aufhänger durchsprechen könnte.



